# Generated by Django 2.2.28 on 2022-06-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokedexCreature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokedexcreature',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
