# Generated by Django 2.2.28 on 2022-06-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PokedexCreature', '0002_pokedexcreature_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokedexcreature',
            name='number',
        ),
    ]
