# Generated by Django 2.2.28 on 2022-06-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='trainer_id',
            field=models.IntegerField(null=True),
        ),
    ]
